-- StreamTube production database blueprint (Phase 2)
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'creator', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS videos (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL, creator_id TEXT NOT NULL REFERENCES users(id), views BIGINT NOT NULL DEFAULT 0, likes BIGINT NOT NULL DEFAULT 0, duration_seconds INTEGER, thumbnail_url TEXT, video_url TEXT, status TEXT NOT NULL DEFAULT 'published', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), creator_id TEXT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, creator_id));
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, video_id TEXT NOT NULL REFERENCES videos(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, video_id TEXT, user_id TEXT, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS earnings (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES users(id), source TEXT NOT NULL, amount NUMERIC(14,4) NOT NULL DEFAULT 0, reference_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS withdrawals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), amount NUMERIC(14,4) NOT NULL, method TEXT, destination TEXT, status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS videos_creator_idx ON videos(creator_id); CREATE INDEX IF NOT EXISTS videos_created_idx ON videos(created_at DESC); CREATE INDEX IF NOT EXISTS comments_video_idx ON comments(video_id); CREATE INDEX IF NOT EXISTS earnings_creator_idx ON earnings(creator_id);
